"""The real apply-at-boot mechanism for the Baseline Install
Configurator's per-tool settings - "one configuration file to rule
them all," per direct instruction: values reviewed/edited in the
configurator artifact should be genuinely applied to the running
system, not just recorded.

Every directive this module builds was researched directly from this
machine's own local man pages this session (`man smartd.conf`,
`man ethtool`), not guessed - see decision record 50. Scoped
deliberately to the two tools with a genuinely rich, real config
surface: `smartmontools` (`smartd.conf`) and `ethtool`. `lm-sensors`/
`nvme-cli` stay passive (confirmed against `sensors.conf(5)` and
nvme-cli's own command set - relabeling raw readings and destructive
maintenance subcommands respectively, neither a real per-boot config
choice); `iperf3`'s extra fields (parallel streams, reverse mode) and
all of "Proxmox Core" (`datacenter.cfg`) are flagged `coded: false` in
the configurator itself and have no apply function here yet - real,
separate follow-up work, not silently promised.

Also covers the two driver/firmware toggles the Drivers & Hardware tab
exposes with a real, single-package apt-get install each
(`apply_cpu_microcode`, `apply_wifi_firmware`) - deliberately not every
driver choice in that tab (GPU mode, passthrough target, and anything
else still marked `coded: false` there have no apply function here
either).

All of this runs post-install, against the already-installed system's
own live files/packages (via `config_pipeline.py`, called from
firstboot) - never against the ISO. Nothing in this module, or in
`config_pipeline.py`, ever reads or writes an ISO/image build
artifact; that is `drive_setup_acquire.py`'s domain and stays entirely
separate from this one.

Same `Runner`-injected, `CommandResult`-returning convention as every
other provisioning module in this codebase. Uses the fuller
`repair.Runner` interface (not the minimal `run()`-only shape other
provisioning modules use) because writing `/etc/smartd.conf` needs
`write_text_atomic`, not just subprocess execution.
"""
from __future__ import annotations

from dataclasses import dataclass

from repair import Runner


SMARTD_CONF_PATH = "/etc/smartd.conf"


@dataclass
class CommandResult:
    ok: bool
    detail: str


# ---------------------------------------------------------------------------
# smartd.conf - pure generation (smartd.conf(5), researched this session)
# ---------------------------------------------------------------------------

def build_smartd_conf(config: dict) -> str:
    """One DEVICESCAN line covering every discovered device, built
    from exactly the directives the configurator's smartmontools tab
    exposes. A directive is only present when its toggle/value implies
    it - an unset email means no -m/-M at all, not empty flags."""
    parts = ["DEVICESCAN"]

    if config.get("smartd_health_check"):
        parts.append("-H")
    if config.get("smartd_monitor_all"):
        parts.append("-a")

    auto_offline = config.get("smartd_auto_offline")
    if auto_offline in ("on", "off"):
        parts += ["-o", auto_offline]

    autosave = config.get("smartd_attribute_autosave")
    if autosave in ("on", "off"):
        parts += ["-S", autosave]

    schedule = config.get("smartd_selftest_schedule")
    if schedule:
        parts += ["-s", schedule]

    email = config.get("smartd_email")
    if email:
        parts += ["-m", email]
        frequency = config.get("smartd_email_frequency")
        if frequency:
            parts += ["-M", frequency]

    return "# Generated by config_apply.py - do not edit by hand\n" + " ".join(parts) + "\n"


def apply_smartd_config(runner: Runner, config: dict) -> CommandResult:
    content = build_smartd_conf(config)
    runner.write_text_atomic(SMARTD_CONF_PATH, content)
    proc = runner.run(["systemctl", "reload-or-restart", "smartd"], timeout=15)
    if proc.returncode != 0:
        return CommandResult(False, f"wrote {SMARTD_CONF_PATH} but reload failed: {proc.stderr.strip()}")
    return CommandResult(True, f"{SMARTD_CONF_PATH} written and smartd reloaded")


# ---------------------------------------------------------------------------
# ethtool - pure argv builders (ethtool(8), researched this session)
# ---------------------------------------------------------------------------

def ethtool_change_argv(interface: str, config: dict) -> list:
    """-s/--change: autoneg, and speed+duplex only when autoneg is
    off (per ethtool(8): speed/duplex are meaningless with autoneg
    on)."""
    argv = ["ethtool", "-s", interface, "autoneg", config.get("ethtool_autoneg", "on")]
    if config.get("ethtool_autoneg") == "off":
        speed = config.get("ethtool_speed")
        if speed:
            argv += ["speed", str(speed)]
        argv += ["duplex", config.get("ethtool_duplex", "full")]
    wol = config.get("ethtool_wol")
    if wol:
        argv += ["wol", wol]
    return argv


def ethtool_offload_argv(interface: str, config: dict) -> list:
    """-K/--offload: only the four most commonly-tuned features this
    project's own diagnostics scope actually cares about (checksum
    rx/tx, tso, gro) - ethtool(8) defines many more (ufo, lro, rxvlan,
    ntuple, ...), deliberately not exposed here."""
    def onoff(key):
        return "on" if config.get(key) else "off"
    return ["ethtool", "-K", interface,
            "rx", onoff("ethtool_rx_checksum"),
            "tx", onoff("ethtool_tx_checksum"),
            "tso", onoff("ethtool_tso"),
            "gro", onoff("ethtool_gro")]


def ethtool_pause_argv(interface: str, config: dict) -> list:
    """-A/--pause: autoneg only - rx/tx pause directives exist in the
    real tool but aren't exposed in the configurator yet."""
    autoneg = "on" if config.get("ethtool_pause_autoneg") else "off"
    return ["ethtool", "-A", interface, "autoneg", autoneg]


def apply_ethtool_config(runner: Runner, interface: str, config: dict) -> CommandResult:
    """Runs -s, then -K, then -A, stopping at the first real failure -
    never attempts a later command once an earlier one fails."""
    for argv in (ethtool_change_argv(interface, config),
                 ethtool_offload_argv(interface, config),
                 ethtool_pause_argv(interface, config)):
        proc = runner.run(argv, timeout=15)
        if proc.returncode != 0:
            return CommandResult(False, f"{argv[1]} failed on {interface}: {proc.stderr.strip()}")
    return CommandResult(True, f"ethtool settings applied to {interface}")


# ---------------------------------------------------------------------------
# Driver/firmware packages - real apt-get installs for the two driver
# toggles the Drivers & Hardware tab actually exposes (decision record on
# the configurator's driver inventory). Package names are specific to
# this project's own real, detected hardware (AMD Ryzen host, MediaTek
# mt7921e Wi-Fi) - not generic placeholders.
# ---------------------------------------------------------------------------

def apply_cpu_microcode(runner: Runner, package: str = "amd64-microcode") -> CommandResult:
    # `package` defaults to this session's own detected CPU vendor
    # (AMD) - that default is only correct when the target matches
    # this machine. A different target (e.g. Intel) must override it
    # via config, never assumed - found missing (no override at all)
    # on audit. DEBIAN_FRONTEND=noninteractive matches
    # firstboot_statemachine.py's own install_diagnostic_tools()
    # convention - a bare apt-get here (also found missing on audit)
    # risks a debconf prompt hanging an unattended firstboot run.
    proc = runner.run(["env", "DEBIAN_FRONTEND=noninteractive", "apt-get", "install", "-y", package],
                       timeout=60)
    if proc.returncode != 0:
        return CommandResult(False, f"{package} install failed: {proc.stderr.strip()}")
    return CommandResult(True, f"{package} installed")


def apply_wifi_firmware(runner: Runner, package: str = "firmware-mediatek") -> CommandResult:
    proc = runner.run(["env", "DEBIAN_FRONTEND=noninteractive", "apt-get", "install", "-y", package],
                       timeout=60)
    if proc.returncode != 0:
        return CommandResult(False, f"{package} install failed: {proc.stderr.strip()}")
    return CommandResult(True, f"{package} installed")


def apply_network_config(runner: Runner, config: dict) -> CommandResult:
    """Apply the hostname; DHCP is already the machine's behaviour, so dhcp=True is
    accepted. Any other link change is refused before any write."""
    if set(config) - {"hostname", "dhcp"} or config.get("dhcp", True) is not True:
        return CommandResult(False, "network not applied: only hostname is supported here; link/DHCP changes require the repair transaction")
    hostname = config.get("hostname")
    if not isinstance(hostname, str) or not hostname.strip() or hostname.startswith("-"):
        return CommandResult(False, "network not applied: a nonempty hostname is required")
    proc = runner.run(["hostnamectl", "set-hostname", hostname], timeout=10)
    if proc.returncode != 0:
        return CommandResult(False, f"hostname set failed: {proc.stderr.strip()}")
    return CommandResult(True, "hostname applied")


def apply_firewall_config(runner: Runner, config: dict) -> CommandResult:
    """LAN-only inbound firewall (see lan_firewall.py): checked, loaded, verified, then persisted."""
    import lan_firewall
    ok, detail = lan_firewall.apply(runner, config)
    return CommandResult(ok, detail)


def apply_ssh_config(runner: Runner, config: dict) -> CommandResult:
    """Apply SSH password authentication settings."""
    password_auth = config.get("password_auth", False)
    setting = "yes" if password_auth else "no"
    try:
        sshd_config = runner.read_text("/etc/ssh/sshd_config") if runner.path_exists("/etc/ssh/sshd_config") else ""
        lines = sshd_config.split("\n")
        new_lines = [l for l in lines if not l.strip().startswith("PasswordAuthentication")]
        new_lines.append(f"PasswordAuthentication {setting}")
        runner.write_text_atomic("/etc/ssh/sshd_config", "\n".join(new_lines))
        proc = runner.run(["systemctl", "restart", "ssh"], timeout=10)
        if proc.returncode != 0:
            return CommandResult(False, f"SSH config written but service restart failed: {proc.stderr.strip()}")
        return CommandResult(True, f"SSH password auth: {setting}")
    except Exception as e:
        return CommandResult(False, f"SSH config failed: {e}")


def apply_tether_config(runner: Runner, config: dict, tether_fn=None) -> CommandResult:
    """Disabled: nothing to apply. Enabled: bring up a real tether interface and report the
    observed stage - success only if an interface actually obtained an address."""
    if not config.get("enabled", False):
        return CommandResult(True, "tether disabled; nothing to apply")
    if tether_fn is None:
        import tether
        tether_fn = tether.auto_tether
    try:
        result = tether_fn()
    except Exception as exc:
        return CommandResult(False, f"tether not applied: bring-up failed: {exc}")
    if result.get("ok") and result.get("address"):
        return CommandResult(True, f"tether up: {result.get('interface')} -> {result['address']}")
    return CommandResult(False, f"tether not applied: stopped at {result.get('stage')}: {result.get('detail')}")


def apply_handoff_config(runner: Runner, config: dict) -> CommandResult:
    """Nothing to restore is a no-op. Named categories need a real archive: it must sit in a backup
    folder, go to /mnt or a Baseline volume, and restoring over user data stays behind
    backup_restore's own fresh-backup gate."""
    if not config.get("restored_categories"):
        return CommandResult(True, "handoff: no categories to restore")
    import backup_restore
    archive, root = config.get("archive_path"), config.get("restore_root")
    if not archive or not root:
        return CommandResult(False, "handoff not applied: categories were named but no archive_path/restore_root was supplied")
    try:
        archive = backup_restore.check_existing_backup_file(runner, archive)
        root = backup_restore.check_restore_root(root)
    except ValueError as exc:
        return CommandResult(False, f"handoff not applied: {exc}")
    result = backup_restore.restore_backup(runner, archive_path=archive, dest_root=root, now=runner.now())
    return CommandResult(result.ok, result.detail if not result.ok else f"handoff restored: {result.detail}")


def _iperf_peer_and_port(config: dict):
    import ipaddress
    peer = config.get("peer_address") or ""
    if not isinstance(peer, str):
        raise ValueError("peer_address must be an IP address on the LAN")
    peer = peer.strip()
    port = config.get("port", 5201)
    if isinstance(port, str) and port.isascii() and port.isdigit():     # settings forms store numbers as text
        port = int(port)
    if not isinstance(port, int) or isinstance(port, bool) or not 1 <= port <= 65535:
        raise ValueError("port must be 1-65535")
    if peer:
        try:
            addr = ipaddress.ip_address(peer)
        except ValueError:
            raise ValueError("peer_address must be an IP address on the LAN") from None
        if addr.is_loopback or addr.is_unspecified or not (addr.is_private or addr.is_link_local):
            raise ValueError("peer_address must be on the LAN (private address)")
    return peer, port


def apply_iperf3_config(runner: Runner, config: dict) -> CommandResult:
    """Client with a LAN peer: one 5-second measured run. Server: one single-use transient unit that
    systemd stops after 10 minutes (the LAN-only firewall already limits who can reach it). No peer:
    only confirm the tool is installed."""
    import json
    try:
        peer, port = _iperf_peer_and_port(config)
    except ValueError as exc:
        return CommandResult(False, f"iperf3 not applied: {exc}")
    if config.get("role", "client") == "server":
        proc = runner.run(["systemd-run", "--unit=baseline-iperf3", "--collect", "--property=RuntimeMaxSec=600",
                           "iperf3", "-s", "-1", "-p", str(port)], timeout=15)
        if proc.returncode != 0:
            return CommandResult(False, f"iperf3 server not started: {proc.stderr.strip()}")
        return CommandResult(True, f"iperf3 server listening on port {port} for one test (stops after 10 minutes)")
    if not peer:
        proc = runner.run(["iperf3", "--version"], timeout=10)
        if proc.returncode != 0:
            return CommandResult(False, "iperf3 is not installed")
        return CommandResult(True, "iperf3 installed; no peer configured, so no test was run")
    proc = runner.run(["iperf3", "-c", peer, "-p", str(port), "-t", "5", "-J"], timeout=30)
    if proc.returncode != 0:
        return CommandResult(False, f"iperf3 test to {peer}:{port} failed: {proc.stderr.strip() or proc.stdout.strip()}")
    try:
        mbps = json.loads(proc.stdout)["end"]["sum_received"]["bits_per_second"] / 1e6
    except (ValueError, KeyError, TypeError):
        return CommandResult(False, f"iperf3 test to {peer}:{port} gave no readable result")
    return CommandResult(True, f"iperf3 to {peer}:{port}: {mbps:.0f} Mbit/s")
