"""Bridge between the Baseline Install Configurator's exported JSON
(install-config.json) and the apply functions in config_apply.py.

Runs post-install, at firstboot, against the already-installed system's
own live files and packages. Never touches an ISO or image-build artifact.

Processes every section the Configurator can export:
  - network (hostname, dhcp)
  - firewall (LAN-only toggle)
  - ssh (password authentication)
  - tether (USB tether mode)
  - handoff (restore categories)
  - proxmox (smartd.conf settings, ethtool tuning)
  - diagnostics.iperf3 (network test config)
  - drivers (cpu_microcode, wifi_firmware package installs)

The config file is generated by settings_web.py's /api/export-config
route (export_install_config()) and placed at /etc/baseline/install-config.json
on the target disk before first boot.
"""
from __future__ import annotations

import json

import config_apply

try:
    from repair import Runner  # type: ignore
except ImportError:  # pragma: no cover - direct-script execution fallback
    class Runner:
        def run(self, argv, timeout=10):
            raise NotImplementedError

        def read_text(self, path):
            raise NotImplementedError

        def path_exists(self, path):
            raise NotImplementedError


DEFAULT_CONFIG_PATH = "/etc/baseline/install-config.json"

_SMARTD_KEYS = (
    "smartd_health_check", "smartd_monitor_all", "smartd_auto_offline",
    "smartd_attribute_autosave", "smartd_selftest_schedule",
    "smartd_email", "smartd_email_frequency",
)
_ETHTOOL_KEYS = (
    "ethtool_autoneg", "ethtool_speed", "ethtool_duplex", "ethtool_wol",
    "ethtool_rx_checksum", "ethtool_tx_checksum", "ethtool_tso",
    "ethtool_gro", "ethtool_pause_autoneg",
)


def load_config(runner: Runner, path: str = DEFAULT_CONFIG_PATH) -> dict | None:
    """None when no config was ever exported - a config file is
    optional; firstboot must proceed without one, applying nothing
    from this pipeline rather than failing."""
    if not runner.path_exists(path):
        return None
    return json.loads(runner.read_text(path))


def _has_any_key(section: dict, keys) -> bool:
    return any(k in section for k in keys)


def apply_stored_config(runner: Runner, config: dict | None, *, network_interface: str) -> dict:
    """Applies every subsystem that has both a real apply function AND
    relevant keys present in the config, independently of the others -
    one subsystem failing (or being absent from the config) never
    skips a different one. Returns {"applied": [...], "skipped": [...],
    "failed": [...]} naming each subsystem, never raising."""
    summary = {"applied": [], "skipped": [], "failed": []}
    if not config:
        summary["skipped"] = [
            "network", "firewall", "ssh", "tether", "handoff",
            "smartd", "ethtool", "iperf3", "cpu_microcode", "wifi_firmware",
        ]
        return summary

    proxmox = config.get("proxmox") or {}
    drivers = config.get("drivers") or {}
    # The exported config's own ethtool_interface field (the configurator's
    # "Interface to inspect/tune" field) wins when the operator actually
    # set one - `network_interface` is only the fallback for a config that
    # omits it. Found on audit: this field's value used to be read and
    # stored but never actually consulted here, silently discarded.
    resolved_interface = proxmox.get("ethtool_interface") or network_interface

    def run_subsystem(name, present, apply_fn):
        if not present:
            summary["skipped"].append(name)
            return
        result = apply_fn()
        (summary["applied"] if result.ok else summary["failed"]).append(name)

    # Network settings
    network = config.get("network") or {}
    run_subsystem("network", bool(network),
                  lambda: config_apply.apply_network_config(runner, network))

    # Firewall
    firewall = config.get("firewall") or {}
    run_subsystem("firewall", bool(firewall),
                  lambda: config_apply.apply_firewall_config(runner, firewall))

    # SSH
    ssh = config.get("ssh") or {}
    run_subsystem("ssh", bool(ssh),
                  lambda: config_apply.apply_ssh_config(runner, ssh))

    # Tether
    tether = config.get("tether") or {}
    run_subsystem("tether", bool(tether),
                  lambda: config_apply.apply_tether_config(runner, tether))

    # Handoff
    handoff = config.get("handoff") or {}
    run_subsystem("handoff", bool(handoff),
                  lambda: config_apply.apply_handoff_config(runner, handoff))

    # Diagnostics tools
    run_subsystem("smartd", _has_any_key(proxmox, _SMARTD_KEYS),
                  lambda: config_apply.apply_smartd_config(runner, proxmox))
    run_subsystem("ethtool", _has_any_key(proxmox, _ETHTOOL_KEYS),
                  lambda: config_apply.apply_ethtool_config(runner, resolved_interface, proxmox))

    # iperf3
    diagnostics = config.get("diagnostics") or {}
    iperf3 = diagnostics.get("iperf3") or {}
    run_subsystem("iperf3", bool(iperf3),
                  lambda: config_apply.apply_iperf3_config(runner, iperf3))

    # Drivers
    run_subsystem("cpu_microcode", bool(drivers.get("cpu_microcode")),
                  lambda: config_apply.apply_cpu_microcode(
                      runner, package=drivers.get("cpu_microcode_package") or "amd64-microcode"))
    run_subsystem("wifi_firmware", bool(drivers.get("nic_wifi_firmware")),
                  lambda: config_apply.apply_wifi_firmware(
                      runner, package=drivers.get("wifi_firmware_package") or "firmware-mediatek"))

    return summary
