"""The real apply-at-boot mechanism for the Baseline Install
Configurator's per-tool settings - "one configuration file to rule
them all," per direct instruction: values reviewed/edited in the
configurator artifact should be genuinely applied to the running
system, not just recorded.

Every directive this module builds was researched directly from this
machine's own local man pages this session (`man smartd.conf`,
`man ethtool`), not guessed - see decision record 50. Scoped
deliberately to the two tools with a genuinely rich, real config
surface: `smartmontools` (`smartd.conf`) and `ethtool`. `lm-sensors`/
`nvme-cli` stay passive (confirmed against `sensors.conf(5)` and
nvme-cli's own command set - relabeling raw readings and destructive
maintenance subcommands respectively, neither a real per-boot config
choice); `iperf3`'s extra fields (parallel streams, reverse mode) and
all of "Proxmox Core" (`datacenter.cfg`) are flagged `coded: false` in
the configurator itself and have no apply function here yet - real,
separate follow-up work, not silently promised.

Also covers the two driver/firmware toggles the Drivers & Hardware tab
exposes with a real, single-package apt-get install each
(`apply_cpu_microcode`, `apply_wifi_firmware`) - deliberately not every
driver choice in that tab (GPU mode, passthrough target, and anything
else still marked `coded: false` there have no apply function here
either).

All of this runs post-install, against the already-installed system's
own live files/packages (via `config_pipeline.py`, called from
firstboot) - never against the ISO. Nothing in this module, or in
`config_pipeline.py`, ever reads or writes an ISO/image build
artifact; that is `drive_setup_acquire.py`'s domain and stays entirely
separate from this one.

Same `Runner`-injected, `CommandResult`-returning convention as every
other provisioning module in this codebase. Uses the fuller
`repair.Runner` interface (not the minimal `run()`-only shape other
provisioning modules use) because writing `/etc/smartd.conf` needs
`write_text_atomic`, not just subprocess execution.
"""
from __future__ import annotations

from dataclasses import dataclass

try:
    from repair import Runner  # type: ignore
except ImportError:  # pragma: no cover - direct-script execution fallback
    class Runner:
        def run(self, argv, timeout=10):
            raise NotImplementedError

        def write_text_atomic(self, path, content):
            raise NotImplementedError


SMARTD_CONF_PATH = "/etc/smartd.conf"


@dataclass
class CommandResult:
    ok: bool
    detail: str


# ---------------------------------------------------------------------------
# smartd.conf - pure generation (smartd.conf(5), researched this session)
# ---------------------------------------------------------------------------

def build_smartd_conf(config: dict) -> str:
    """One DEVICESCAN line covering every discovered device, built
    from exactly the directives the configurator's smartmontools tab
    exposes. A directive is only present when its toggle/value implies
    it - an unset email means no -m/-M at all, not empty flags."""
    parts = ["DEVICESCAN"]

    if config.get("smartd_health_check"):
        parts.append("-H")
    if config.get("smartd_monitor_all"):
        parts.append("-a")

    auto_offline = config.get("smartd_auto_offline")
    if auto_offline in ("on", "off"):
        parts += ["-o", auto_offline]

    autosave = config.get("smartd_attribute_autosave")
    if autosave in ("on", "off"):
        parts += ["-S", autosave]

    schedule = config.get("smartd_selftest_schedule")
    if schedule:
        parts += ["-s", schedule]

    email = config.get("smartd_email")
    if email:
        parts += ["-m", email]
        frequency = config.get("smartd_email_frequency")
        if frequency:
            parts += ["-M", frequency]

    return "# Generated by config_apply.py - do not edit by hand\n" + " ".join(parts) + "\n"


def apply_smartd_config(runner: Runner, config: dict) -> CommandResult:
    content = build_smartd_conf(config)
    runner.write_text_atomic(SMARTD_CONF_PATH, content)
    proc = runner.run(["systemctl", "reload-or-restart", "smartd"], timeout=15)
    if proc.returncode != 0:
        return CommandResult(False, f"wrote {SMARTD_CONF_PATH} but reload failed: {proc.stderr.strip()}")
    return CommandResult(True, f"{SMARTD_CONF_PATH} written and smartd reloaded")


# ---------------------------------------------------------------------------
# ethtool - pure argv builders (ethtool(8), researched this session)
# ---------------------------------------------------------------------------

def ethtool_change_argv(interface: str, config: dict) -> list:
    """-s/--change: autoneg, and speed+duplex only when autoneg is
    off (per ethtool(8): speed/duplex are meaningless with autoneg
    on)."""
    argv = ["ethtool", "-s", interface, "autoneg", config.get("ethtool_autoneg", "on")]
    if config.get("ethtool_autoneg") == "off":
        speed = config.get("ethtool_speed")
        if speed:
            argv += ["speed", str(speed)]
        argv += ["duplex", config.get("ethtool_duplex", "full")]
    wol = config.get("ethtool_wol")
    if wol:
        argv += ["wol", wol]
    return argv


def ethtool_offload_argv(interface: str, config: dict) -> list:
    """-K/--offload: only the four most commonly-tuned features this
    project's own diagnostics scope actually cares about (checksum
    rx/tx, tso, gro) - ethtool(8) defines many more (ufo, lro, rxvlan,
    ntuple, ...), deliberately not exposed here."""
    def onoff(key):
        return "on" if config.get(key) else "off"
    return ["ethtool", "-K", interface,
            "rx", onoff("ethtool_rx_checksum"),
            "tx", onoff("ethtool_tx_checksum"),
            "tso", onoff("ethtool_tso"),
            "gro", onoff("ethtool_gro")]


def ethtool_pause_argv(interface: str, config: dict) -> list:
    """-A/--pause: autoneg only - rx/tx pause directives exist in the
    real tool but aren't exposed in the configurator yet."""
    autoneg = "on" if config.get("ethtool_pause_autoneg") else "off"
    return ["ethtool", "-A", interface, "autoneg", autoneg]


def apply_ethtool_config(runner: Runner, interface: str, config: dict) -> CommandResult:
    """Runs -s, then -K, then -A, stopping at the first real failure -
    never attempts a later command once an earlier one fails."""
    for argv in (ethtool_change_argv(interface, config),
                 ethtool_offload_argv(interface, config),
                 ethtool_pause_argv(interface, config)):
        proc = runner.run(argv, timeout=15)
        if proc.returncode != 0:
            return CommandResult(False, f"{argv[1]} failed on {interface}: {proc.stderr.strip()}")
    return CommandResult(True, f"ethtool settings applied to {interface}")


# ---------------------------------------------------------------------------
# Driver/firmware packages - real apt-get installs for the two driver
# toggles the Drivers & Hardware tab actually exposes (decision record on
# the configurator's driver inventory). Package names are specific to
# this project's own real, detected hardware (AMD Ryzen host, MediaTek
# mt7921e Wi-Fi) - not generic placeholders.
# ---------------------------------------------------------------------------

def apply_cpu_microcode(runner: Runner) -> CommandResult:
    proc = runner.run(["apt-get", "install", "-y", "amd64-microcode"], timeout=60)
    if proc.returncode != 0:
        return CommandResult(False, f"amd64-microcode install failed: {proc.stderr.strip()}")
    return CommandResult(True, "amd64-microcode installed")


def apply_wifi_firmware(runner: Runner, package: str = "firmware-mediatek") -> CommandResult:
    proc = runner.run(["apt-get", "install", "-y", package], timeout=60)
    if proc.returncode != 0:
        return CommandResult(False, f"{package} install failed: {proc.stderr.strip()}")
    return CommandResult(True, f"{package} installed")
