"""Unit tests for config_diff.py - real read-back of the target
system's CURRENT state for the four subsystems config_pipeline.py can
actually apply (smartd, ethtool, cpu_microcode, wifi_firmware), and a
pure diff against a DESIRED exported config. This is the real engine
behind the configurator's "DIFFERENCES" page - no real smartd/ethtool/
dpkg is ever invoked, the FakeRunner records/returns everything.

The smartd.conf round-trip is exact by construction: config_apply.
build_smartd_conf() controls the only format ever written, so parsing
it back is a real, deterministic round-trip, not a guess. The ethtool
read-back format is real, standard `ethtool(8)`/`ethtool -k`/
`ethtool -a` output shape - the same one `man ethtool` and every real
Linux system produce.
"""
from fake_runner import FakeProc, FakeRunner

import config_diff as cd


# -- smartd.conf read-back -------------------------------------------------

def test_read_current_smartd_config_absent_file_returns_all_defaults():
    runner = FakeRunner()  # /etc/smartd.conf not present
    current = cd.read_current_smartd_config(runner)
    assert current == {
        "smartd_health_check": False, "smartd_monitor_all": False,
        "smartd_auto_offline": "", "smartd_attribute_autosave": "",
        "smartd_selftest_schedule": "", "smartd_email": "", "smartd_email_frequency": "",
    }


def test_read_current_smartd_config_parses_a_real_generated_file():
    content = ("# Generated by config_apply.py - do not edit by hand\n"
               "DEVICESCAN -H -a -o on -S on -s L/../../7/03 -m ops@example.com -M daily\n")
    runner = FakeRunner(files={"/etc/smartd.conf": content})
    current = cd.read_current_smartd_config(runner)
    assert current == {
        "smartd_health_check": True, "smartd_monitor_all": True,
        "smartd_auto_offline": "on", "smartd_attribute_autosave": "on",
        "smartd_selftest_schedule": "L/../../7/03",
        "smartd_email": "ops@example.com", "smartd_email_frequency": "daily",
    }


def test_read_current_smartd_config_omitted_email_directives_read_back_blank():
    content = "# Generated by config_apply.py - do not edit by hand\nDEVICESCAN -H -a -o on -S on -s L/../../7/03\n"
    runner = FakeRunner(files={"/etc/smartd.conf": content})
    current = cd.read_current_smartd_config(runner)
    assert current["smartd_email"] == ""
    assert current["smartd_email_frequency"] == ""


# -- ethtool read-back -------------------------------------------------

ETHTOOL_SETTINGS_OUTPUT = """Settings for eth0:
	Supported ports: [ TP ]
	Speed: 1000Mb/s
	Duplex: Full
	Auto-negotiation: on
	Wake-on: g
	Link detected: yes
"""

ETHTOOL_FEATURES_OUTPUT = """Features for eth0:
rx-checksumming: on
tx-checksumming: on
	tx-checksum-ipv4: off [fixed]
tcp-segmentation-offload: on
generic-receive-offload: off
"""

ETHTOOL_PAUSE_OUTPUT = """Pause parameters for eth0:
Autonegotiate:	on
RX:		off
TX:		off
"""


def test_read_current_ethtool_config_parses_real_tool_output():
    runner = FakeRunner(command_responses=[
        (lambda a: a[:1] == ["ethtool"] and len(a) == 2, FakeProc(0, ETHTOOL_SETTINGS_OUTPUT, "")),
        (lambda a: a[:2] == ["ethtool", "-k"], FakeProc(0, ETHTOOL_FEATURES_OUTPUT, "")),
        (lambda a: a[:2] == ["ethtool", "-a"], FakeProc(0, ETHTOOL_PAUSE_OUTPUT, "")),
    ])
    current = cd.read_current_ethtool_config(runner, "eth0")
    assert current == {
        "ethtool_autoneg": "on", "ethtool_speed": "1000", "ethtool_duplex": "full", "ethtool_wol": "g",
        "ethtool_rx_checksum": True, "ethtool_tx_checksum": True,
        "ethtool_tso": True, "ethtool_gro": False,
        "ethtool_pause_autoneg": True,
    }


def test_read_current_ethtool_config_handles_a_real_command_failure():
    runner = FakeRunner(command_responses=[
        (lambda a: a[:1] == ["ethtool"], FakeProc(1, "", "no such device")),
    ])
    current = cd.read_current_ethtool_config(runner, "eth0")
    assert current["ethtool_autoneg"] == ""


# -- package installed check -------------------------------------------------

def test_read_current_package_installed_true():
    runner = FakeRunner(command_responses=[
        (lambda a: a[:1] == ["dpkg-query"], FakeProc(0, "install ok installed", "")),
    ])
    assert cd.read_current_package_installed(runner, "amd64-microcode") is True


def test_read_current_package_installed_false_when_not_installed():
    runner = FakeRunner(command_responses=[
        (lambda a: a[:1] == ["dpkg-query"], FakeProc(1, "", "package not found")),
    ])
    assert cd.read_current_package_installed(runner, "amd64-microcode") is False


# -- pure diff engine -------------------------------------------------

def test_diff_config_reports_changed_and_unchanged_keys():
    current = {"a": 1, "b": 2, "c": 3}
    desired = {"a": 1, "b": 99, "c": 3}
    result = cd.diff_config(current, desired)
    by_key = {row["key"]: row for row in result}
    assert by_key["a"]["changed"] is False
    assert by_key["b"]["changed"] is True
    assert by_key["b"]["current"] == 2
    assert by_key["b"]["desired"] == 99
    assert by_key["c"]["changed"] is False


def test_diff_config_only_reports_keys_present_in_desired():
    current = {"a": 1, "unrelated_key": "x"}
    desired = {"a": 1}
    result = cd.diff_config(current, desired)
    assert [row["key"] for row in result] == ["a"]


def test_diff_config_treats_a_missing_current_key_as_changed():
    current = {}
    desired = {"a": 1}
    result = cd.diff_config(current, desired)
    assert result[0]["changed"] is True
    assert result[0]["current"] is None


# -- top-level: builds the full DIFFERENCES report -------------------------

def test_compute_full_diff_covers_all_four_real_subsystems():
    runner = FakeRunner(command_responses=[
        (lambda a: a[:1] == ["ethtool"] and len(a) == 2, FakeProc(0, ETHTOOL_SETTINGS_OUTPUT, "")),
        (lambda a: a[:2] == ["ethtool", "-k"], FakeProc(0, ETHTOOL_FEATURES_OUTPUT, "")),
        (lambda a: a[:2] == ["ethtool", "-a"], FakeProc(0, ETHTOOL_PAUSE_OUTPUT, "")),
        (lambda a: a[:1] == ["dpkg-query"] and "amd64-microcode" in a, FakeProc(1, "", "not found")),
        (lambda a: a[:1] == ["dpkg-query"] and "firmware-mediatek" in a, FakeProc(0, "install ok installed", "")),
    ])
    desired_config = {
        "proxmox": {"smartd_health_check": True, "ethtool_speed": "1000"},
        "drivers": {"cpu_microcode": True, "cpu_microcode_package": "amd64-microcode",
                    "nic_wifi_firmware": True, "wifi_firmware_package": "firmware-mediatek"},
    }
    report = cd.compute_full_diff(runner, desired_config, network_interface="eth0")
    sections = {s["subsystem"] for s in report}
    assert sections == {"smartd", "ethtool", "cpu_microcode", "wifi_firmware"}
    smartd_section = next(s for s in report if s["subsystem"] == "smartd")
    assert any(row["key"] == "smartd_health_check" and row["changed"] for row in smartd_section["changes"])
    cpu_section = next(s for s in report if s["subsystem"] == "cpu_microcode")
    assert cpu_section["changes"][0]["changed"] is True  # not installed yet, desired wants it
    wifi_section = next(s for s in report if s["subsystem"] == "wifi_firmware")
    assert wifi_section["changes"][0]["changed"] is False  # already installed, matches desired
