"""Unit tests for update_pipeline.py - selective application of an
exported config against an EXISTING install, per direct instruction:
"the update action... should also allow applying only code updates
and or DRIVERS and or Applications AND or OS installs AND or only
update configs" with configs "selectable as update or not update in
any combination."

Real, honest scope: "code", "applications", and "os" have no real
apply mechanism anywhere in this codebase yet (confirmed by decision
records 51/53/54's own audits) - selecting them is real (recorded in
the summary as `not_available`), applying them is not, and this module
never pretends otherwise. "drivers" and "configs" (smartd/ethtool) DO
have real apply functions (config_apply.py) and are genuinely wired
here, including true partial-field selection for configs: an
unselected field is read back from the target's own CURRENT state
(config_diff.py) and preserved exactly, never reset to a default -
this is what "any combination" actually requires for a whole-file
rewrite like smartd.conf.
"""
from fake_runner import FakeProc, FakeRunner

import update_pipeline as up

CONFIG = {
    "proxmox": {
        "smartd_health_check": True, "smartd_monitor_all": True,
        "smartd_auto_offline": "on", "smartd_attribute_autosave": "on",
        "smartd_selftest_schedule": "L/../../7/03", "smartd_email": "", "smartd_email_frequency": "",
        "ethtool_autoneg": "on", "ethtool_speed": "", "ethtool_duplex": "full", "ethtool_wol": "g",
        "ethtool_rx_checksum": True, "ethtool_tx_checksum": True, "ethtool_tso": True, "ethtool_gro": True,
        "ethtool_pause_autoneg": True,
    },
    "drivers": {
        "cpu_microcode": True, "cpu_microcode_package": "amd64-microcode",
        "nic_wifi_firmware": True, "wifi_firmware_package": "firmware-mediatek",
    },
}


def test_code_applications_os_are_reported_not_available_not_silently_dropped():
    runner = FakeRunner()
    summary = up.apply_selective_update(
        runner, CONFIG, {"code": True, "applications": True, "os": True}, network_interface="eno1")
    assert set(summary["not_available"]) == {"code", "applications", "os"}
    assert summary["applied"] == []
    assert runner.calls == []  # nothing real was even attempted


def test_drivers_category_off_skips_both_driver_packages_entirely():
    runner = FakeRunner()
    summary = up.apply_selective_update(runner, CONFIG, {"drivers": False}, network_interface="eno1")
    assert "cpu_microcode" in summary["skipped"]
    assert "wifi_firmware" in summary["skipped"]
    assert not any("apt-get" in c for c in runner.calls)


def test_drivers_category_on_applies_both_real_packages():
    runner = FakeRunner()
    summary = up.apply_selective_update(runner, CONFIG, {"drivers": True}, network_interface="eno1")
    assert "cpu_microcode" in summary["applied"]
    assert "wifi_firmware" in summary["applied"]
    assert any("amd64-microcode" in c for c in runner.calls)
    assert any("firmware-mediatek" in c for c in runner.calls)


def test_configs_off_entirely_skips_smartd_and_ethtool():
    runner = FakeRunner()
    summary = up.apply_selective_update(runner, CONFIG, {"configs": False}, network_interface="eno1")
    assert "smartd" in summary["skipped"]
    assert "ethtool" in summary["skipped"]
    assert "/etc/smartd.conf" not in runner.writes


def test_configs_true_applies_every_field():
    runner = FakeRunner()
    summary = up.apply_selective_update(runner, CONFIG, {"configs": True}, network_interface="eno1")
    assert "smartd" in summary["applied"]
    assert "ethtool" in summary["applied"]
    assert "/etc/smartd.conf" in runner.writes


def test_configs_partial_selection_preserves_unselected_fields_from_the_targets_current_state():
    """The crux of "any combination": selecting only
    smartd_health_check for update must not reset smartd_monitor_all
    (or anything else) to blank - it should come from what's actually
    on the target right now."""
    existing_smartd = ("# Generated by config_apply.py - do not edit by hand\n"
                        "DEVICESCAN -a -o off -S off -s S/../.././02 -m old@example.com -M once\n")
    runner = FakeRunner(files={"/etc/smartd.conf": existing_smartd})
    summary = up.apply_selective_update(
        runner, CONFIG, {"configs": ["smartd_health_check"]}, network_interface="eno1")
    assert "smartd" in summary["applied"]
    written = runner.files["/etc/smartd.conf"]
    assert "-H" in written          # the one field we selected to update
    assert "-a" in written           # preserved from the target's current state, not reset
    assert "-o off" in written       # preserved
    assert "-s S/../.././02" in written  # preserved
    assert "old@example.com" in written  # preserved


def test_configs_partial_selection_only_touches_the_selected_subsystem():
    """Selecting only a smartd_ key must not also rewrite ethtool -
    each real subsystem only runs when at least one of its own keys
    was actually selected."""
    runner = FakeRunner()
    summary = up.apply_selective_update(
        runner, CONFIG, {"configs": ["smartd_health_check"]}, network_interface="eno1")
    assert "smartd" in summary["applied"]
    assert "ethtool" in summary["skipped"]
    assert not any(c[:1] == ["ethtool"] for c in runner.calls)


def test_all_categories_together():
    runner = FakeRunner()
    summary = up.apply_selective_update(
        runner, CONFIG,
        {"code": True, "drivers": True, "applications": True, "os": True, "configs": True},
        network_interface="eno1")
    assert set(summary["not_available"]) == {"code", "applications", "os"}
    assert set(summary["applied"]) == {"cpu_microcode", "wifi_firmware", "smartd", "ethtool"}
