"""A drive that holds data, and does not carry a UUID generated by the installer, can never be formatted:
not by a parameter, not by a human confirmation, not by a standing approval. No real drive is read or written."""
import pytest
from fake_runner import FakeRunner
from test_drive_admin import FakePdsRunner

import drive_admin as da
import drive_guard as dg
import hitl
from hitl_helpers import authorize, perform_confirmed

GUID = "11111111-2222-3333-4444-555555555555"
DATA = f"sdb disk  {GUID} \nsdb1 part ntfs  Media\n"
OWN = f"sdb disk  {GUID} \nsdb1 part ext4  BASELINE\nsdb2 part ext4  USER_ADMIN\n"


def pds(table):
    return FakePdsRunner(drive_table=table)


def test_prepare_refuses_a_data_drive_so_no_challenge_can_be_raised():
    with pytest.raises(ValueError, match="installer"):
        da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=pds(DATA))


@pytest.mark.parametrize("extra", [{}, {"force": True}, {"confirmed": True}, {"i_know": "yes"}])
def test_no_parameter_gets_a_data_drive_formatted(extra):
    runner = FakeRunner()
    result = da.perform_action(runner, "build_self_installer", {"device_path": "/dev/sdb", **extra},
                               pds_runner=pds(DATA))
    assert result.ok is False
    assert runner.calls == []


def test_a_human_confirmation_does_not_override_the_data_rule():
    runner = FakeRunner()
    ok_pds = pds("sdb disk  " + GUID + " \n")
    auth, store = authorize("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=ok_pds)
    # The same authorization, replayed against a drive that now holds data, still gets nothing.
    result = da.perform_action(runner, "build_self_installer", {"device_path": "/dev/sdb"},
                               pds_runner=pds(DATA), authorization=auth, hitl_store=store)
    assert result.ok is False
    assert runner.calls == []


def test_a_data_drive_with_an_unregistered_uuid_is_refused_even_when_all_volumes_are_baselines_own():
    with pytest.raises(ValueError):
        da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=pds(OWN))


def test_an_unreadable_drive_is_treated_as_having_data():
    class Broken(FakePdsRunner):
        def run(self, argv):
            if argv[0] == "lsblk" and "NAME,TYPE,FSTYPE,PTUUID,LABEL" in argv:
                raise OSError("no lsblk")
            return super().run(argv)
    with pytest.raises(ValueError):
        da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=Broken())


def test_a_blank_drive_may_be_prepared():
    assert da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=pds(f"sdb disk  {GUID} \n"))


def test_a_data_drive_carrying_a_registered_installer_uuid_may_be_prepared():
    dg.register_installer_uuid(GUID, serial="MD89N41071210AP4E")
    assert da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=pds(DATA))


def test_rebuild_persistence_lvm_wipes_nothing_on_a_data_drive():
    runner, p = FakeRunner(), pds(DATA)
    result = da.rebuild_persistence_lvm(runner, device_path="/dev/sdb", pds_runner=p)
    assert result.ok is False
    assert p.wipe_calls == [] and runner.calls == []


def test_self_installer_pipeline_refuses_a_data_drive_by_itself(tmp_path):
    import self_installer as si

    class Untouchable:
        def __getattr__(self, name):
            raise AssertionError("the pipeline went past the data check")
    p = pds(DATA)
    result = si.build_and_write_self_installer(
        device_path="/dev/sdb", device_min_size_bytes=1, pds_runner=p, acquire_runner=Untouchable(),
        answer_runner=Untouchable(), iso_builder_runner=Untouchable(), install_runner=Untouchable(),
        workspace=tmp_path, repo_root=tmp_path, assistant_binary=tmp_path / "x")
    assert result.outcome == "refused" and "installer" in result.detail


def test_stamp_needs_a_human_confirmation():
    result = da.perform_action(FakeRunner(), "stamp_installer_identity", {"device_path": "/dev/sdb"},
                               pds_runner=pds(DATA))
    assert result.ok is False
    assert hitl.VERBS["stamp_installer_identity"] == "STAMP"


def test_stamp_adopts_a_baseline_only_drive_end_to_end(monkeypatch):
    table = {"v": OWN}
    monkeypatch.setattr(dg, "_default_run", lambda argv: (0, table["v"]))
    runner = FakeRunner()
    orig = runner.run

    def run(argv, **kw):
        if argv[0] == "sgdisk":
            table["v"] = f"sdb disk  {argv[2]} \nsdb1 part ext4  BASELINE\nsdb2 part ext4  USER_ADMIN\n"
        return orig(argv, **kw)
    runner.run = run
    result = perform_confirmed(runner, "stamp_installer_identity", {"device_path": "/dev/sdb"}, pds_runner=pds(OWN))
    assert result.ok is True, result.message if hasattr(result, "message") else result
    new_guid = table["v"].split()[2]
    assert dg.is_installer_uuid(new_guid)
    # ...and the drive may now be formatted by the installer.
    dg.require_may_format("/dev/sdb")


def test_stamp_refuses_a_drive_with_someone_elses_data(monkeypatch):
    monkeypatch.setattr(dg, "_default_run", lambda argv: (0, DATA))
    runner = FakeRunner()
    result = perform_confirmed(runner, "stamp_installer_identity", {"device_path": "/dev/sdb"}, pds_runner=pds(DATA))
    assert result.ok is False
    assert not any(c[0] == "sgdisk" for c in runner.calls)


def test_a_baseline_drive_with_data_is_not_formatted_without_a_recent_backup(monkeypatch):
    dg.register_installer_uuid(GUID, serial="MD89N41071210AP4E")
    monkeypatch.setattr(da, "backup_is_fresh", lambda: False)
    with pytest.raises(ValueError, match="backup"):
        da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=pds(OWN))
    monkeypatch.setattr(da, "backup_is_fresh", lambda: True)
    assert da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=pds(OWN))


def test_a_blank_drive_needs_no_backup(monkeypatch):
    monkeypatch.setattr(da, "backup_is_fresh", lambda: False)
    assert da.prepare_action("build_self_installer", {"device_path": "/dev/sdb"}, pds_runner=pds(f"sdb disk  {GUID} \n"))


def test_freshness_check_failing_to_look_counts_as_no_backup(monkeypatch):
    import backup_restore

    def boom(*a, **k):
        raise OSError("x")
    monkeypatch.setattr(backup_restore, "has_recent_successful_backup", boom)
    assert da._read_backup_freshness() is False
